// <auto-generated />
using Coterie.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coterie.Db.Migrations
{
    [DbContext(typeof(CoterieDbContext))]
    [Migration("20221005064230_StateHasDataMigration")]
    partial class StateHasDataMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Coterie.Db.Tables.State", b =>
                {
                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceFactor")
                        .HasColumnType("TEXT");

                    b.HasKey("ShortName");

                    b.HasIndex("LongName");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            ShortName = "FL",
                            LongName = "FLORIDA",
                            PriceFactor = 1.2m
                        },
                        new
                        {
                            ShortName = "OH",
                            LongName = "OHIO",
                            PriceFactor = 1m
                        },
                        new
                        {
                            ShortName = "TX",
                            LongName = "TEXAS",
                            PriceFactor = 0.943m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
