// <auto-generated />
using Coterie.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coterie.Db.Migrations
{
    [DbContext(typeof(CoterieDbContext))]
    partial class CoterieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Coterie.Db.Tables.State", b =>
                {
                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceFactor")
                        .HasColumnType("TEXT");

                    b.HasKey("ShortName");

                    b.HasIndex("LongName");

                    b.ToTable("States");
                });
#pragma warning restore 612, 618
        }
    }
}
